"""VulnClaw PoC Builder — auto-generate PoC scripts for verified vulnerabilities."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Optional

from vulnclaw.agent.context import SessionState, VulnerabilityFinding


# ── Python PoC Template ─────────────────────────────────────────────

PYTHON_POC_TEMPLATE = '''\
#!/usr/bin/env python3
"""
PoC: {{ title }}
Severity: {{ severity }}
{% if cve %}CVE: {{ cve }}{% endif %}
Generated by VulnClaw on {{ generated_at }}

Usage:
    python {{ filename }} --target TARGET_URL [--cmd COMMAND]
"""

import argparse
import sys

try:
    import requests
except ImportError:
    print("[!] Please install requests: pip install requests")
    sys.exit(1)


class PoC:
    """PoC for {{ title }}."""

    def __init__(self, target: str):
        self.target = target.rstrip("/")
        self.session = requests.Session()
        self.session.verify = False  # For self-signed certs in test environments
        self.session.headers.update({
            "User-Agent": "VulnClaw-PoC/0.1",
        })

    def verify(self) -> bool:
        """Verify the vulnerability exists."""
        # TODO: Implement verification logic based on the vulnerability type
        # This is a template - replace with actual verification code

        try:
            url = f"{self.target}/"
            response = self.session.get(url, timeout=10)
            print(f"[*] Target responded with status: {response.status_code}")
            return True
        except requests.RequestException as e:
            print(f"[-] Request failed: {e}")
            return False

    def exploit(self, cmd: str = "id") -> Optional[str]:
        """Execute the exploit and return the output."""
        # TODO: Implement exploitation logic
        # This is a template - replace with actual exploit code

        print(f"[*] Attempting to execute: {cmd}")
        print("[!] Exploit logic not yet implemented - customize based on findings")
        return None


def main():
    parser = argparse.ArgumentParser(description="PoC: {{ title }}")
    parser.add_argument("target", help="Target URL, e.g. http://192.168.1.100")
    parser.add_argument("--cmd", default="id", help="Command to execute (default: id)")
    parser.add_argument("--verify-only", action="store_true", help="Only verify, don't exploit")
    args = parser.parse_args()

    poc = PoC(args.target)

    print(f"[*] Target: {args.target}")
    print(f"[*] Verifying vulnerability...")

    if poc.verify():
        print("[+] Vulnerability confirmed!")
    else:
        print("[-] Vulnerability not confirmed")
        sys.exit(1)

    if not args.verify_only:
        print(f"[*] Exploiting with command: {args.cmd}")
        result = poc.exploit(args.cmd)
        if result:
            print(f"[+] Result:\\n{result}")
        else:
            print("[-] Exploitation failed")


if __name__ == "__main__":
    main()
'''


def generate_pocs(session: SessionState, output_dir: Path) -> list[Path]:
    """Generate PoC scripts for all findings in the session.

    Args:
        session: Current session state with findings.
        output_dir: Directory to write PoC files.

    Returns:
        List of paths to generated PoC files.
    """
    from jinja2 import Template

    output_dir.mkdir(parents=True, exist_ok=True)
    generated = []

    for i, finding in enumerate(session.findings, 1):
        # Generate filename
        safe_name = finding.title.replace(" ", "_").replace("/", "_")[:40]
        cve_suffix = f"_{finding.cve}" if finding.cve else ""
        filename = f"poc_{i:02d}_{safe_name}{cve_suffix}.py"

        # Render template
        template = Template(PYTHON_POC_TEMPLATE)
        content = template.render(
            title=finding.title,
            severity=finding.severity,
            cve=finding.cve,
            generated_at=datetime.now().isoformat(),
            filename=filename,
        )

        output_path = output_dir / filename
        output_path.write_text(content, encoding="utf-8")
        generated.append(output_path)

        # Update finding with PoC path
        finding.poc_script = str(output_path)

    return generated


def generate_single_poc(
    title: str,
    severity: str = "High",
    cve: Optional[str] = None,
    target: str = "http://TARGET",
    vuln_type: str = "",
) -> str:
    """Generate a single PoC script string.

    Returns the PoC Python code as a string.
    """
    from jinja2 import Template

    template = Template(PYTHON_POC_TEMPLATE)
    return template.render(
        title=title,
        severity=severity,
        cve=cve,
        generated_at=datetime.now().isoformat(),
        filename=f"poc_{vuln_type or 'custom'}.py",
    )
